default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: mairie_dev
  username: imidsac
  password: <%= ENV['PASSWORD'] %>


production:
  <<: *default
  database: mairie_pro
  username: imidsac
  password: <%= ENV['PASSWORD'] %>


test:
  <<: *default
  database: mairie_test
  username: imidsac
  password: <%= ENV['PASSWORD'] %>
